keys:
    - &mnas age1etyreuzxhj3j7hem6wt7jlra5a9lgy9d94fp09sp58p4stwlyunqt5n4hv
creation_rules:
    - path_regex: nixos/.*\.sops\.yaml$
      key_groups:
        - age:
            - age153gpfdw58csvgxj3vn9ym2g3zx7mfhaldyz5uvvrfajne8htj3asjqrp7h
            - *mnas
