{ config, lib, pkgs, imports, modulesPath, ... }:

with lib;
{
  # NOTE
  # Some 'global' areas have defaults set in their respective modules.
  # These will be applied when the modules are loaded
  # Not the global role.
  # Not sure at this point a good way to manage globals in one place
  # without mono-repo config.

  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix") # Generated by nixos-config-generate
      ./global
    ];

  config = {

    boot.tmp.cleanOnBoot = true;

    mySystem = {

      # basics for all devices
      time.timeZone = "Australia/Melbourne";
      # security.increaseWheelLoginLimits = true;
      system.packages = [ pkgs.bat ];
      domain = "spiceratops.cloud";
      internalDomain = "spiceratops.dev";

      shell.fish.enable = true;
      # But wont enable plugins globally, leave them for workstations
      #TODO system.resticBackup.remote.location = "s3:https://xxxxxxxxxxxxxxxxxxxxxxxx.r2.cloudflarestorage.com/nixos-restic";
    };

    environment.systemPackages = with pkgs; [
      curl
      wget
      dnsutils
      tree
      powertop
      parted
      smartmontools
    ];

    networking.useDHCP = lib.mkDefault true;
    networking.domain = config.mySystem.domain;

    powerManagement.powertop.enable = true;
  };

}
